[tool.black]
line-length = 140

[tool.flake8]
max-line-length = 140
ignore = "D100, D105, D107, D200"
per-file-ignores = "test/*:D101,D102,D103"

[tool.mypy]
python_version = 3.8
warn_return_any = true
follow_imports = "silent"
ignore_missing_imports = true
show_column_numbers = true

[tool.isort]
profile = "black"
length_sort = true

[tool.pytest.ini_options]
minversion = "7.0"
addopts = [
    "-ra",
    "-q",
    "--import-mode=importlib",
]
filterwarnings = ["ignore::DeprecationWarning"]
